# Generated by Django 4.1.6 on 2023-02-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Группировка')),
                ('content', models.TextField(verbose_name='О группировке')),
            ],
            options={
                'verbose_name': 'Группировка',
                'verbose_name_plural': 'Группировки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Образование')),
                ('content', models.TextField(verbose_name='Об учреждении')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Произведение')),
                ('about', models.TextField(verbose_name='О произведении')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведении',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Институция')),
                ('content', models.TextField(verbose_name='Об институции')),
            ],
            options={
                'verbose_name': 'Институция',
                'verbose_name_plural': 'Институции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exhibition', verbose_name='Произведение')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя художника')),
                ('years_of_life', models.CharField(blank=True, max_length=255, verbose_name='Даты жизни')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.association', verbose_name='Группировка')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.education', verbose_name='Образование')),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exhibition', verbose_name='Произведение')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.institution', verbose_name='Институции')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
                'ordering': ['name'],
            },
        ),
    ]
